# Generated by Django 2.1.4 on 2018-12-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('dish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Dish')),
                ('size', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Dinner Platters',
            },
            bases=('orders.dish',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('dish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Dish')),
            ],
            options={
                'db_table': 'Pasta',
            },
            bases=('orders.dish',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('dish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Dish')),
                ('size', models.CharField(max_length=1)),
                ('mod', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Pizzas',
            },
            bases=('orders.dish',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('dish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Dish')),
            ],
            options={
                'db_table': 'Salads',
            },
            bases=('orders.dish',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('dish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Dish')),
                ('size', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Subs',
            },
            bases=('orders.dish',),
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('dish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Dish')),
            ],
            options={
                'db_table': 'Toppings',
            },
            bases=('orders.dish',),
        ),
    ]
