# Generated by Django 2.1.4 on 2018-12-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Customer Orders',
        ),
    ]
