# Generated by Django 2.1.4 on 2018-12-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181204_1902'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Orders',
        ),
    ]
