# Generated by Django 2.1.4 on 2018-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181204_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.ManyToManyField(blank=True, related_name='Articles', to='orders.Dish'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
