# Generated by Django 2.1.4 on 2018-12-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181204_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='mod',
            new_name='mode',
        ),
    ]
